### ISSUE TITLE
Why not proof.py?

### ISSUE THREAD

**Issue by NiklasRosenstein** [onyxfish/proof#8]
Any reason the library is a package and not a single Python module?

**Comment by onyxfish** [comment]
To be honest, I never considered doing it another way, but if I needed a reason it's because I like to have the flexibility to divide classes into separate modules as the code base matures and becomes more complex.

Is there a particular reason you were prefer it to be packaged as a module?

**Comment by NiklasRosenstein** [comment]
Just a personal preference, keeping tight things tight. Was wondering if you had a special reason other than personal preference. ;)
